version: '2'

services:
  api:
    restart: always
    build: ./api
    expose:
      - "8000"
    volumes:
      - /usr/src/app/web/project/static
      - ./db:/home/flask/app/web/db
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app.py

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - api
    depends_on:
      - api