version: '3'

services:
  api:
    container_name: mmr-api-flask
    hostname: sheldon-mmr-api-flask
    restart: unless-stopped
    build: ./api
    expose:
      - "8000"
    volumes:
      - /usr/src/app/web/project/static
      - ./db:/home/flask/app/web/db
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    container_name: mmr-api-nginx
    hostname: sheldon-mmr-api-nginx
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
#    volumes_from:
#      - api
#    depends_on:
#      - api
#
#volumes:
