version: '3'

services:
  flask:
    restart: unless-stopped
    build: ./api
    expose:
      - "8000"
    volumes:
      - /usr/src/app/web/project/static
      - ./db:/home/flask/app/web/db
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    networks:
      - default
      - website

#  db:
#    image: postgres
#    networks:
#      - default

networks:
  website:
    external:
      name: ssessner_com_proxy_website
