version: '3'

services:
  flask:
    restart: unless-stopped
    build: .
    expose:
      - 8000
    environment:
      DATABASE_URL: postgres://mmr-api:example@db:5432/mmr-api
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    networks:
      - default
      - website
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: mmr-api
      POSTGRES_PASSWORD: example
    networks:
      - default

networks:
  website:
    external:
      name: ssessner_com_proxy_website
